package tropicraft.asm;

import java.util.Arrays;
import java.util.Map;
import java.util.logging.Logger;

import tropicraft.ModInfo;
import net.minecraftforge.event.ForgeSubscribe;

import com.google.common.eventbus.EventBus;

import cpw.mods.fml.common.DummyModContainer;
import cpw.mods.fml.common.FMLLog;
import cpw.mods.fml.common.LoadController;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPostInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.relauncher.IFMLLoadingPlugin;
import cpw.mods.fml.relauncher.IFMLLoadingPlugin.MCVersion;
import cpw.mods.fml.relauncher.IFMLLoadingPlugin.TransformerExclusions;
import cpw.mods.fml.relauncher.Side;
import cpw.mods.fml.relauncher.SideOnly;
/*
 * Don't let any access transformer stuff accidentally modify our classes
 * A list of package prefixes for FML to ignore
 */
@SideOnly(Side.CLIENT)
@TransformerExclusions({"tropicraft.asm" , "tropicraft"})
@MCVersion("1.6.4")
public class TropicraftCorePlugin extends DummyModContainer implements IFMLLoadingPlugin {

	private final String[] asmTransformers = new String[]{"tropicraft.asm.ModelBipedTransformer", "tropicraft.asm.RenderPlayerTransformer"};
    private final ModMetadata modMeta = new ModMetadata();
    
    public static Logger logger = Logger.getLogger("Tropicraft-Core");
    
    public TropicraftCorePlugin() {
    	logger.setParent(FMLLog.getLogger());
    	logger.info("Starting to load Tropicraft CoreMods!");
    	logger.info("Constructing preloader (Modules: " + Arrays.toString(asmTransformers) + ")");
    	
    	modMeta.autogenerated = false;
    	modMeta.credits = "Tropicraft team";
    	modMeta.modId = getModId();
        modMeta.version = getVersion();
        modMeta.name = getName();
        modMeta.authorList = Arrays.asList("See Tropicraft's mcmod.info!");
    }
    
    @ForgeSubscribe
    public void preInit(FMLPreInitializationEvent evt) {

    }

    @ForgeSubscribe
    public void init(FMLInitializationEvent evt) {

    }

    @ForgeSubscribe
    public void postInit(FMLPostInitializationEvent evt) {

    }

    @Override
    public String getModId() {
        return "Tropicraft-Coremods";
    }

    @Override
    public String getName() {
        return "Tropicraft Coremods";
    }

    @Override
    public String getVersion() {
        return ModInfo.VERSION;
    }

    @Override
    public String getDisplayVersion() {
        return getVersion();
    }

    @Override
    public boolean registerBus(EventBus bus, LoadController controller) {
        bus.register(this);
        return true;
    }
    
    @Override
    public ModMetadata getMetadata() {
        return modMeta;
    }

	@Override
	/*
	 * Use if you want to download libraries. Returns a list of classes that implement the ILibrarySet interface
	 * eg return new String[] { "tutorial.asm.downloaders.DownloadUsefulLibrary " };
	 */
	public String[] getLibraryRequestClass() {
		return null;
	}
	/*
	 * The class(es) that do(es) the transforming. Needs to implement IClassTransformer in some way
	 */

	@Override

	public String[] getASMTransformerClass() {
		return asmTransformers;
	}
	/*
	 * The class that acts similarly to the @Mod annotation.
	 */
	@Override
	public String getModContainerClass() {
		return "tropicraft.asm.TropicraftCorePlugin";
	}
	/*
	 * If you want to do stuff BEFORE minecraft starts, but after your mod is loaded.
	 */
	@Override
	public String getSetupClass() {
		return null;
	}
	/*
	 * Gives the mod coremod data if it wants it.
	 */
	@Override
	public void injectData(Map<String, Object> data) {

	}

}