// Date: 10/29/2011 2:19:36 AM
// Java generated by Techne
// This is the first stage to more output options
// and therefore a very basic Render-File
// I hope it will be useful, in any case, leave
// feedback so I can improve on it
// - ZeuX
package tropicraft.client.entities;

import net.minecraft.client.renderer.entity.RenderLiving;
import net.minecraft.entity.Entity;
import net.minecraft.entity.EntityLiving;
import tropicraft.client.entities.models.ModelFailgull;

public class RenderFailgull extends RenderLiving
{

	public RenderFailgull(float f)
	{
		super(new ModelFailgull(), f);
	}

	public void renderNew(EntityLiving entityliving, double d, double d1, double d2, 
			float f, float f1)
	{
		super.doRenderLiving(entityliving, d, d1, d2, f, f1);
	}

	public void doRenderLiving(EntityLiving entityliving, double d, double d1, double d2, 
			float f, float f1)
	{
		renderNew(entityliving, d, d1, d2, f, f1);
	}

	public void doRender(Entity entity, double d, double d1, double d2, 
			float f, float f1)
	{
		renderNew((EntityLiving)entity, d, d1, d2, f, f1);
	}
}
