package tropicraft.registry;

import net.minecraft.block.Block;
import net.minecraft.client.renderer.entity.Render;
import net.minecraft.entity.Entity;
import tropicraft.client.entities.RenderAshen;
import tropicraft.client.entities.RenderChair;
import tropicraft.client.entities.RenderDart;
import tropicraft.client.entities.RenderEIH;
import tropicraft.client.entities.RenderEagleRay;
import tropicraft.client.entities.RenderEchinodermEgg;
import tropicraft.client.entities.RenderFailgull;
import tropicraft.client.entities.RenderFallingPurifiedSand;
import tropicraft.client.entities.RenderFishHook;
import tropicraft.client.entities.RenderFlyingBlock;
import tropicraft.client.entities.RenderIguana;
import tropicraft.client.entities.RenderKoaMan;
import tropicraft.client.entities.RenderLostMask;
import tropicraft.client.entities.RenderManOWar;
import tropicraft.client.entities.RenderMarlin;
import tropicraft.client.entities.RenderProjectileSprite;
import tropicraft.client.entities.RenderSeaUrchin;
import tropicraft.client.entities.RenderSnareTrap;
import tropicraft.client.entities.RenderSpiderEgg;
import tropicraft.client.entities.RenderStarfish;
import tropicraft.client.entities.RenderTCItemFrame;
import tropicraft.client.entities.RenderTreeFrog;
import tropicraft.client.entities.RenderTropiCreeper;
import tropicraft.client.entities.RenderTropiSkeleton;
import tropicraft.client.entities.RenderTropiSpider;
import tropicraft.client.entities.RenderTropicalFish;
import tropicraft.client.entities.RenderTurtle;
import tropicraft.client.entities.RenderTurtleEgg;
import tropicraft.client.entities.RenderUmbrella;
import tropicraft.client.entities.RenderVMonkey;
import tropicraft.client.entities.RenderWallMask;
import tropicraft.client.entities.RenderWallShell;
import tropicraft.client.entities.RenderWallStarfish;
import tropicraft.client.entities.models.ModelAshen;
import tropicraft.client.entities.models.ModelEIH;
import tropicraft.client.entities.models.ModelFish;
import tropicraft.client.entities.models.ModelIguana;
import tropicraft.client.entities.models.ModelKoaMan;
import tropicraft.client.entities.models.ModelManOWar;
import tropicraft.client.entities.models.ModelMarlin;
import tropicraft.client.entities.models.ModelSpiderEgg;
import tropicraft.client.entities.models.ModelTreeFrog;
import tropicraft.client.entities.models.ModelTurtle;
import tropicraft.client.entities.models.ModelTurtleEgg;
import tropicraft.client.entities.models.ModelVMonkey;
import tropicraft.client.entities.particles.EntityFireballFX;
import tropicraft.entities.EntityEagleRay;
import tropicraft.entities.blocks.EntityFallingPurifiedSand;
import tropicraft.entities.hostile.land.Creeper;
import tropicraft.entities.hostile.land.EIH;
import tropicraft.entities.hostile.land.Skeleton;
import tropicraft.entities.hostile.land.SpiderAdult;
import tropicraft.entities.hostile.land.SpiderChild;
import tropicraft.entities.hostile.land.SpiderEgg;
import tropicraft.entities.hostile.land.TreeFrog;
import tropicraft.entities.hostile.land.tribes.ashen.AshenHunter;
import tropicraft.entities.hostile.land.tribes.ashen.LostMask;
import tropicraft.entities.hostile.land.tribes.koa.EntityKoaManly;
import tropicraft.entities.hostile.land.tribes.koa.v3.EntityKoaBase;
import tropicraft.entities.items.EntityTCItemFrame;
import tropicraft.entities.items.EntityWallStarfish;
import tropicraft.entities.items.WallMask;
import tropicraft.entities.items.WallShell;
import tropicraft.entities.passive.flying.Failgull;
import tropicraft.entities.passive.land.Iguana;
import tropicraft.entities.passive.land.VMonkey;
import tropicraft.entities.passive.water.EntityManOWar;
import tropicraft.entities.passive.water.EntityMarlin;
import tropicraft.entities.passive.water.EntitySeaTurtle;
import tropicraft.entities.passive.water.EntitySeaUrchin;
import tropicraft.entities.passive.water.EntitySeaUrchinEgg;
import tropicraft.entities.passive.water.EntityStarfish;
import tropicraft.entities.passive.water.EntityStarfishEgg;
import tropicraft.entities.passive.water.EntityTropicalFish;
import tropicraft.entities.passive.water.EntityTurtleEgg;
import tropicraft.entities.placeable.EntityChair;
import tropicraft.entities.placeable.EntitySnareTrap;
import tropicraft.entities.placeable.EntityUmbrella;
import tropicraft.entities.projectiles.EntityCoconutGrenade;
import tropicraft.entities.projectiles.EntityDart;
import tropicraft.entities.projectiles.EntityFireBall;
import tropicraft.entities.projectiles.EntityIceBall;
import tropicraft.entities.projectiles.EntityTameBall;
import tropicraft.entities.projectiles.EntityTropicraftLeafballNew;
import tropicraft.fishing.EntityHook;
import tropicraft.fishing.RenderFishingHook;
import tropicraft.items.TropicraftItems;
import CoroAI.entity.EntityTropicalFishHook;
import cpw.mods.fml.client.registry.RenderingRegistry;
import extendedrenderer.particle.entity.EntityBreakingRotFX;
import extendedrenderer.particle.entity.EntityIconFX;
import extendedrenderer.render.RenderNull;

public class TCRenderRegistry {

	/**
	 * Add all render mappings here
	 */
	public static void init() {
		addMapping(EntityKoaManly.class, new RenderKoaMan(new ModelKoaMan(), 0.5F));
		addMapping(Skeleton.class, new RenderTropiSkeleton(0.5F));
		addMapping(Creeper.class, new RenderTropiCreeper());
		addMapping(TreeFrog.class, new RenderTreeFrog(new ModelTreeFrog(), 0.5F));
		addMapping(LostMask.class, new RenderLostMask());
		addMapping(EIH.class, new RenderEIH(new ModelEIH(), 0.5F));
		addMapping(Iguana.class, new RenderIguana(new ModelIguana(), 0.5F));
		addMapping(VMonkey.class, new RenderVMonkey(new ModelVMonkey(), 0.5F));
		//addMapping(EntityDart.class, new RenderDart());
		//addMapping(Ashen.class, new RenderAshen(new ModelAshen(), 0.25F));
		addMapping(AshenHunter.class, new RenderAshen(new ModelAshen(), 0.25F));
		addMapping(EntityTropicalFish.class, new RenderTropicalFish(new ModelFish(), 0.25F));
		addMapping(EntityDart.class, new RenderDart());
		addMapping(WallShell.class, new RenderWallShell());
	    addMapping(EntitySnareTrap.class, new RenderSnareTrap());
	    addMapping(Failgull.class, new RenderFailgull(0.5F));
	    addMapping(EntitySeaUrchin.class, new RenderSeaUrchin());
	    addMapping(EntitySeaUrchinEgg.class, new RenderEchinodermEgg());
	    addMapping(EntityFallingPurifiedSand.class, new RenderFallingPurifiedSand());
	    addMapping(EntityChair.class, new RenderChair());
	    addMapping(EntityUmbrella.class, new RenderUmbrella());
	    addMapping(EntityStarfish.class, new RenderStarfish());
	    addMapping(EntityStarfishEgg.class, new RenderEchinodermEgg());
	    addMapping(EntityWallStarfish.class, new RenderWallStarfish());
	    addMapping(EntityEagleRay.class, new RenderEagleRay());
	    addMapping(EntityTropicraftLeafballNew.class, new RenderProjectileSprite(TropicraftItems.leafBall));
	    addMapping(EntityFireBall.class, new RenderFlyingBlock(Block.netherrack));
	    addMapping(EntityIceBall.class, new RenderFlyingBlock(Block.ice));
	    addMapping(EntityTameBall.class, new RenderFlyingBlock(Block.mobSpawner));
	    //addMapping(EntityIceBall.class, new RenderProjectileSprite(TropicraftItems.iceBall));
	    addMapping(EntityBreakingRotFX.class, new RenderNull());
	    addMapping(EntityIconFX.class, new RenderNull());
	    addMapping(EntityFireballFX.class, new RenderNull());
	    addMapping(EntityMarlin.class, new RenderMarlin(new ModelMarlin(), 0.5f));
	    addMapping(EntityManOWar.class, new RenderManOWar(new ModelManOWar(32, 20, true), new ModelManOWar(0, 20, false), .35F));
	    addMapping(EntityTCItemFrame.class, new RenderTCItemFrame());
	    addMapping(EntityKoaBase.class, new RenderKoaMan(new ModelKoaMan(), 0.7F));
	    addMapping(EntitySeaTurtle.class, new RenderTurtle(new ModelTurtle(), 0.5F));
        addMapping(EntityTurtleEgg.class, new RenderTurtleEgg(new ModelTurtleEgg(), .025F));
        addMapping(WallMask.class, new RenderWallMask());
        addMapping(EntityTropicalFishHook.class, new RenderFishHook());
        addMapping(EntityHook.class, new RenderFishingHook());
        addMapping(EntityCoconutGrenade.class, new RenderProjectileSprite(TropicraftItems.coconutBomb));
        addMapping(SpiderAdult.class, new RenderTropiSpider());
        addMapping(SpiderChild.class, new RenderTropiSpider());
        addMapping(SpiderEgg.class, new RenderSpiderEgg(new ModelSpiderEgg(), 0.5F));
	}
	
	private static void addMapping(Class<? extends Entity> entityClass, Render render) {
		RenderingRegistry.registerEntityRenderingHandler(entityClass, render);
	}
}
